spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test1
          uri: https://google.com
          predicates:
            - Query=url,google
  application:
    name: mall-gateway


server:
  port: 88

