spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test1
          uri: https://google.com
          predicates:
            - Query=url,google
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/mallproduct/**
          filters:
            #因為mall-product的路徑前綴設為mallproduct，所以需這樣寫，如果為product可改為下:
            #- RewritePath=/api/(?<segment>/?.*),/$\{segment
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}

  application:
    name: mall-gateway


server:
  port: 8888

